# Generated by Django 2.1 on 2018-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideator',
            name='username',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
