# Generated by Django 2.1 on 2018-08-28 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180828_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideator',
            name='section',
        ),
        migrations.AddField(
            model_name='ideator',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ideator',
            name='coutry',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ideator',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ideator',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ideator',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ideator',
            name='state',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='ideator',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
