# Generated by Django 2.1 on 2018-08-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180828_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideator',
            old_name='coutry',
            new_name='country',
        ),
    ]
