# Generated by Django 2.1 on 2018-08-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180828_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideator',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=8),
        ),
    ]
