# Generated by Django 2.1 on 2018-08-28 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180828_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
