# Generated by Django 2.1 on 2018-08-28 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneur',
            name='department',
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='Is_investor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='country',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='state',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
