# Generated by Django 2.1 on 2018-08-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='description',
            field=models.CharField(default='description', max_length=30),
        ),
    ]
