# Generated by Django 2.1 on 2018-08-24 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_ideas_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Ideator'),
        ),
    ]
