# Generated by Django 2.1 on 2018-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20180824_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='expectation',
            field=models.CharField(blank=True, default='lkdjkfjskldfkjklsd lksdfkjjskdf lksdfjkjf', max_length=2000),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='description',
            field=models.CharField(default='description', max_length=3000),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
