# Generated by Django 2.1 on 2018-08-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20180825_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='Is_patent',
            field=models.BooleanField(default=False),
        ),
    ]
