# Generated by Django 2.1 on 2018-09-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_ideas_is_patent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideas',
            old_name='user',
            new_name='ideator',
        ),
    ]
